# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fga < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.2.5"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.2.5/fga_0.2.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "cc5dd623d512a7463a705aceb0d99f8ffe49de7c7a698b50a3387cc0ef0724c0"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.2.5/fga_0.2.5_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "8f08c17e67cba769302ab32d2e1d429e7a152ccbf5ec1c32b1d0d630a0a42c6d"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.2.5/fga_0.2.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "bb0cbad6c11c314dc350f1275252c76f36af07014daa558c2b6dd8780c5afeba"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.2.5/fga_0.2.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "86ac73a521fa9b4c8eca29c87bd6231922b9352dd9785c18d1b1240248d03e68"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
