# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fga < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.2.0"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.2.0/fga_0.2.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "78542bfc6ff6292461e3ba9528f6334f149b546cee806d875018e0806ac1c641"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.2.0/fga_0.2.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9c3ed2d6e8a8243f0f88c71172ca4417e1087c2453f3b2f793c50b498f2492be"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.2.0/fga_0.2.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b3eba70e16e0d5fe85b95ea421615ae81b3c5573e4bd17e230743bedd8e2642b"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.2.0/fga_0.2.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a4b8fd513d14dca8066c5b7e0cc71c326b042e102340ac4a7d706d3da02e3c31"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
