# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fga < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.1.0-beta6"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.1.0-beta6/fga_0.1.0-beta6_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "625986054dff34671fc3ba0589d30df40411cf6ef7b77c353c451513137e5671"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.1.0-beta6/fga_0.1.0-beta6_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6d0387066129e3735b560a8f30d1523d008da62617652e9fc9e63ec68dcaa818"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.1.0-beta6/fga_0.1.0-beta6_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "cbe16f97b1fab46d8375a18cceafd4ca28d2f664d9e816be3478a3d3f49f46f8"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.1.0-beta6/fga_0.1.0-beta6_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "86d7c9c0c695b4004572c6938da4f3e2cd3f0bbab7a809eeabf51dd4eb2fbf06"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
