# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FgaAT0716 < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.7.16"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.7.16/fga_0.7.16_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b12fbfcbdbc3ab666ac9619c617d650746e56145fa582c62fe405bac9f8f75c2"

      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.7.16/fga_0.7.16_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5ce8f82a4b2541c973caa5231052324edf5a20b3b963d15da8a05ecd04accd49"

      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.16/fga_0.7.16_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "1e8ccb918cf6f0cdfc22142afd1b2b54f25df956356c1f7c26a97ddd186cc86a"
      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.16/fga_0.7.16_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b5993ad24a8ce3311d527a47c90c5dcf41a81f69abd34864e55e1dde5714e016"
      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
