# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FgaAT0710 < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.7.10"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.7.10/fga_0.7.10_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "3213485c466c359b256c88d2db100549d38ced1c91d79100ff38f46576e23d56"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.7.10/fga_0.7.10_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d3377286db8358fa22b3feefe344c67312ad0cf8983b5c2daa7a29cf5b1469ca"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.10/fga_0.7.10_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f17120e4ede3d6f138c8db09e8bead3a8da6ac541f16f096249f8881737d208f"
      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.10/fga_0.7.10_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "79f3224180e4586a60610584a75c8e16b2dc35199d0de0a0d62d76863483646a"
      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
