# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FgaAT0717 < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.7.17"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.7.17/fga_0.7.17_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "1c013e0930dbfa2415d47d233a22ef7854600f9a053ab54a57bca326f9d8f12f"

      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.7.17/fga_0.7.17_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3c098270bcebd144adcb06796ac79ca5f2e1e8abfed13ebae6a0adc2ef727fcc"

      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.17/fga_0.7.17_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "1fd6c75811c0e650b9318e86c98a3083fcc568d08ddbfdf63b75b77408a51d3e"
      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.17/fga_0.7.17_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5722e27529f0cb8e977e4eb456f0fd7ac23044cbb2126bf3ae82f0922e792316"
      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
