# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FgaAT0714Beta1 < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.7.14-beta.1"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.7.14-beta.1/fga_0.7.14-beta.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "20f917a832254b2f3d1e2877159a4fdd6d8b1e8dd2b436ad71bee7a85ed0dd8c"

      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.7.14-beta.1/fga_0.7.14-beta.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "59dd68221ac7ee9c64c8fcbed1067e4bd6bf99c58da8175540c8de597ef51923"

      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.14-beta.1/fga_0.7.14-beta.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c5269e2694df63f6c193896eb5c5d6b189a301e619abe37b3d07ce5435941809"
      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.14-beta.1/fga_0.7.14-beta.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9b6516c4473eda6ba8b6026609164e1fbd2947d85242b2fde6c291e4a0b16a26"
      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
