# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FgaAT0720 < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.7.20"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0be76e333e6970546300f1e1ff22d599351a65e09879292b0dc79af8d4aa6d19"

      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f481da61d4a2dee8dac279227401f9ecbe5bdb051c546bf64c1d4e9c027b1ba3"

      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f0136868bdced6f8fded1876d41aa8d594d23588183497f6d876c1a5343529a4"
      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.7.20/fga_0.7.20_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6acb3158fd46fa706344664df9a1d9433d9ec6322044bdcbf952126e7e098760"
      define_method(:install) do
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "fga"
        zsh_completion.install "completions/fga.zsh" => "_fga"
        fish_completion.install "completions/fga.fish"
        man1.install "manpages/fga.1.gz"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
