# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openfga < Formula
  desc "A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar."
  homepage "https://openfga.dev/"
  version "1.14.2"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/openfga/releases/download/v1.14.2/openfga_1.14.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "a600defb2b15f33cf7070d609c774bcf79c9251fa037cae980b554c87a9dcaaa"

      define_method(:install) do
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/openfga/releases/download/v1.14.2/openfga_1.14.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2f57469b85137ba8e77c71e20b2ba998653eed9e7d60f0b8bfb23d0658b35463"

      define_method(:install) do
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/openfga/releases/download/v1.14.2/openfga_1.14.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "5ea9d3846b21a0a3ea7009fe9c7e294a33bc73a0a9020f30b5443ead101258cd"
      define_method(:install) do
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/openfga/releases/download/v1.14.2/openfga_1.14.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5fe6c3dfd966a64ff0060f1bb6dc23a7a7132306c550f763924a3928023bfe00"
      define_method(:install) do
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
  end

  head "https://github.com/openfga/openfga.git", :branch => "main"

  test do
    system "#{bin}/openfga version"
  end
end
