# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenfgaCli < Formula
  desc "A cross-platform CLI to interact with an OpenFGA server."
  homepage "https://openfga.dev/"
  version "0.1.0-beta1"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.1.0-beta1/openfga-cli_0.1.0-beta1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "1f74312c667e686d8beb964f4c98474e614907c92b42a638b8e6b60370b2bbc7"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "goreleaser"
        zsh_completion.install "completions/fga.zsh" => "_goreleaser"
        fish_completion.install "completions/fga.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/cli/releases/download/v0.1.0-beta1/openfga-cli_0.1.0-beta1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3563bbc36730e19510b24f46431bb9c98eb18a4aed2b704f0b89ed95dfe2ad06"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "goreleaser"
        zsh_completion.install "completions/fga.zsh" => "_goreleaser"
        fish_completion.install "completions/fga.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/cli/releases/download/v0.1.0-beta1/openfga-cli_0.1.0-beta1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "3e2a9f0d140c9578eff77716bcfd804e52f2ad90978ea646bd891b033b9ed6de"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "goreleaser"
        zsh_completion.install "completions/fga.zsh" => "_goreleaser"
        fish_completion.install "completions/fga.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/cli/releases/download/v0.1.0-beta1/openfga-cli_0.1.0-beta1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "022051a6d970fd9bcffd1e36d2d1262ee45f8dd1880eaa9032f7267b3a32c9e1"

      def install
        bin.install "fga"
        bash_completion.install "completions/fga.bash" => "goreleaser"
        zsh_completion.install "completions/fga.zsh" => "_goreleaser"
        fish_completion.install "completions/fga.fish"
      end
    end
  end

  head "https://github.com/openfga/cli.git", :branch => "main"

  test do
    system "#{bin}/fga version"
  end
end
