# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openfga < Formula
  desc "A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar."
  homepage "https://openfga.dev/"
  version "1.12.0"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/openfga/releases/download/v1.12.0/openfga_1.12.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "49f3c88dffcf87d6d5f834efa8e1e05d01b2f1aa25fa77a66052ae2f798c77cc"

      define_method(:install) do
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/openfga/releases/download/v1.12.0/openfga_1.12.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d0f09f9fa58a8eec667ba4c3bd40d2fc96d930f8b059691d8edd271ee7fbb782"

      define_method(:install) do
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/openfga/releases/download/v1.12.0/openfga_1.12.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c2e0efb8f6adce651f7631f94841614303e6b302c8b01fb40f8c55bcc40fad6a"
      define_method(:install) do
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfga/openfga/releases/download/v1.12.0/openfga_1.12.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b3b5d7901d65400510f4e4911ef9b415df5fc8a414af44d80b0cacaea714f0ae"
      define_method(:install) do
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
  end

  head "https://github.com/openfga/openfga.git", :branch => "main"

  test do
    system "#{bin}/openfga version"
  end
end
