# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openfga < Formula
  desc "A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar."
  homepage "https://openfga.dev/"
  version "1.8.9"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfga/openfga/releases/download/v1.8.9/openfga_1.8.9_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0efa8e8a4d04dfdf21449c317d9626dda147b9982fe491b28d70855f634e95a0"

      def install
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfga/openfga/releases/download/v1.8.9/openfga_1.8.9_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "115181fdf565601eb803868d734ffda7a8d4a822b451366bc4df91b6748f02bf"

      def install
        bin.install "openfga"
        bash_completion.install "completions/openfga.bash" => "goreleaser"
        zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
        fish_completion.install "completions/openfga.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/openfga/openfga/releases/download/v1.8.9/openfga_1.8.9_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "a3123260754323b7c592f8218179feccdee0e12851e241cd4fe53b509dc4bf5b"

        def install
          bin.install "openfga"
          bash_completion.install "completions/openfga.bash" => "goreleaser"
          zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
          fish_completion.install "completions/openfga.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/openfga/openfga/releases/download/v1.8.9/openfga_1.8.9_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "0978aa24057f1183c4a0a11a24f31c4f89c26ee95144d51ab7c07301563ea5af"

        def install
          bin.install "openfga"
          bash_completion.install "completions/openfga.bash" => "goreleaser"
          zsh_completion.install "completions/openfga.zsh" => "_goreleaser"
          fish_completion.install "completions/openfga.fish"
        end
      end
    end
  end

  head "https://github.com/openfga/openfga.git", :branch => "main"

  test do
    system "#{bin}/openfga version"
  end
end
